# Generated by Django 3.1.2 on 2020-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
